org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.3.3. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.